[workspace]
resolver = "2"

members = [
    "espeak-phonemizer",
    "libtorch-inference",
    "sonic-sys",
    "audio-ops"
]

[patch.crates-io]
libtashkeel_base = { path = "./deps/libtashkeel/libtashkeel_base" }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
