name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ piper_tetun ]
  pull_request:
    branches: [ piper_tetun ]

jobs:
  build:
    runs-on: windows-latest
    name: "build: windows-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]

    steps:
      - name: ⚡ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # PREP protoc
      - name: ⚡ Prepare protoc 
        uses: actions/cache@v4
        id: protoc
        with:
          path: protoc
          key: https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-win64.zip
      - name: ⚡ Download protoc 
        if: steps.protoc.outputs.cache-hit != 'true'
        run: curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-win64.zip
      - name: ⚡ Extract protoc
        if: steps.protoc.outputs.cache-hit != 'true'
        run: unzip -qq protoc.zip -d protoc

      # PREP libtorch
      - name: ⚡ Prepare libtorch 
        uses: actions/cache@v4
        id: libtorch
        with:
          path: libtorch
          key: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.1.0%2Bcpu.zip
      - name: ⚡ Download libtorch 
        if: steps.libtorch.outputs.cache-hit != 'true'
        run: curl -o libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.1.0%2Bcpu.zip
      - name: ⚡ Extract libtorch
        if: steps.libtorch.outputs.cache-hit != 'true'
        run: unzip -qq libtorch.zip -d libtorch

      # Run cargo build
      - name: ⚡ Cargo Cache
        id: cargo-fetch
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          save-always: 'true'
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo
      - name: 🔨Cargo Fetch
        uses: actions-rs/cargo@v1
        if: steps.cargo-fetch.outputs.cache-hit != 'true'
        with:
          command: fetch
        env:
          LIBTORCH: ${{github.workspace}}/libtorch/libtorch/
          PROTOC: ${{github.workspace}}/protoc/bin/protoc

      - name: ⚡ Cargo Target Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - name: 🔨Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          LIBTORCH: ${{github.workspace}}/libtorch/libtorch/
          PROTOC: ${{github.workspace}}/protoc/bin/protoc
      - name: check
        if: always()
        run: |
          ls ./target/debug/build/