name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ piper_tetun ]
  pull_request:
    branches: [ piper_tetun ]

jobs:
  build:
    runs-on: windows-latest
    name: "build: ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]

    steps:

      - uses: actions/download-artifact@v4
        with:
          name: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.2.2%2Bcpu.zip
          path: libtorch.zip
      - name: check
        run: ls
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ⚡ Cargo Cache
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo

      - name: ⚡ Cargo Target Cache
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build

