name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ piper_tetun ]
  pull_request:
    branches: [ piper_tetun ]

jobs:
  build:
    runs-on: windows-latest
    name: "build: ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: cargo
        run: cargo build

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}